# Generated by Django 2.2.5 on 2019-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
